// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// card update
export const UPDATE_LIMIT_REQUEST = 'UPDATE_LIMIT_REQUEST';
export const CHANGE_LIMIT_STATUS = 'CHANGE_LIMIT_STATUS';
export const GET_CARD_INFO_REQUEST = 'GET_CARD_INFO_REQUEST';
export const GET_CARD_INFO_RESPONSE = 'GET_CARD_INFO_RESPONSE';
